import { EyeOff, RotateCcw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { relativeDays } from '@/lib/utils';
import { DIRECTION_META } from '@/lib/nri/directions';
import { DirectionChip, BandBadge } from './DirectionChip';
import type { Explanation, Direction } from '@/lib/api';

/**
 * The explainability panel.
 *
 * This is the component the entire NRI design exists to make possible: a score,
 * every reason that produced it, and the exact weight each reason contributed.
 * The weights sum to the score, so a staff member who distrusts the number can
 * add it up by hand and either agree or find the rule they disagree with.
 *
 * Nothing here is generated by a model. If that ever changes, this panel is
 * where it has to be disclosed.
 */
export function SignalExplanation({
  explanation, onDismiss, onRestore, compact = false,
}: {
  explanation: Explanation;
  onDismiss?: (direction: Direction) => void;
  onRestore?: (direction: Direction) => void;
  compact?: boolean;
}) {
  const meta = DIRECTION_META[explanation.direction];
  const isDismissed = explanation.dismissed;

  return (
    <div
      className={cn(
        'rounded-lg border p-4',
        isDismissed ? 'border-dashed opacity-60' : 'bg-card',
      )}
    >
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <DirectionChip
              direction={explanation.direction}
              score={explanation.score}
              band={explanation.band}
              showLabel
            />
            <BandBadge band={explanation.band} />
            {isDismissed && (
              <span className="text-xs text-muted-foreground">Dismissed</span>
            )}
          </div>
          <p className="mt-2 text-sm">{explanation.summary}</p>
        </div>

        {!compact && (
          <div className="shrink-0">
            {isDismissed
              ? onRestore && (
                  <Button variant="ghost" size="sm" onClick={() => onRestore(explanation.direction)}>
                    <RotateCcw /> Restore
                  </Button>
                )
              : onDismiss && explanation.score >= 25 && (
                  <Button variant="ghost" size="sm" onClick={() => onDismiss(explanation.direction)}>
                    <EyeOff /> I&rsquo;ve seen this
                  </Button>
                )}
          </div>
        )}
      </div>

      {explanation.reasons.length > 0 && (
        <div className="mt-3">
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
            Why — these weights add up to {explanation.score}
          </p>
          <ul className="mt-2 space-y-1.5">
            {explanation.reasons.map((reason) => (
              <li key={reason.code} className="flex items-start gap-3 text-sm">
                <span className="mt-0.5 w-8 shrink-0 text-right font-mono text-xs tabular text-muted-foreground">
                  +{reason.weight}
                </span>
                <span className="min-w-0">
                  <span className="font-medium">{reason.label}</span>
                  {reason.detail && (
                    <span className="text-muted-foreground"> — {reason.detail}</span>
                  )}
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {!compact && explanation.score >= 25 && (
        <div className="mt-3 rounded border-l-2 border-primary bg-muted/40 px-3 py-2">
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
            What to do
          </p>
          <p className="mt-0.5 text-sm">{meta.response}</p>
        </div>
      )}

      <p className="mt-3 text-xs text-muted-foreground">
        Scored by {explanation.source} · updated {relativeDays(explanation.updated_at)}
      </p>
    </div>
  );
}
