-- ─────────────────────────────────────────────────────────────────────────────
-- Auxilium 0001 — initial schema
--
-- Conventions used everywhere in this database:
--   • IDs are prefixed random tokens (mem_…, hh_…, need_…). Generated by
--     src/lib/ids.ts — never by the database.
--   • Money is ALWAYS integer cents. There is no REAL column for currency here
--     and there never should be.
--   • Timestamps are ISO-8601 UTC strings ('2026-07-25T21:00:00.000Z'), which
--     sort lexicographically and survive D1's type affinity without surprises.
--   • Every tenant-scoped table carries org_id and is indexed on it first.
--     There is no such thing as a query without the tenant scope.
--   • Soft deletes use deleted_at; live queries filter deleted_at IS NULL.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Tenancy ──────────────────────────────────────────────────────────────────

CREATE TABLE organizations (
  id            TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  slug          TEXT NOT NULL UNIQUE,
  -- White-label CMS shell: ministry-branded portal settings live here as JSON
  -- so a ministry can be rebranded without a migration.
  brand         TEXT NOT NULL DEFAULT '{}',
  -- 'demo' orgs are exempt from destructive guards and get reset on a schedule.
  kind          TEXT NOT NULL DEFAULT 'ministry' CHECK (kind IN ('ministry', 'demo')),
  timezone      TEXT NOT NULL DEFAULT 'America/Chicago',
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL,
  deleted_at    TEXT
);

CREATE TABLE users (
  id             TEXT PRIMARY KEY,
  org_id         TEXT NOT NULL REFERENCES organizations(id),
  email          TEXT NOT NULL,
  name           TEXT NOT NULL,
  -- PBKDF2-derived; salt is stored alongside. Never reversible, never exported.
  password_hash  TEXT,
  password_salt  TEXT,
  role           TEXT NOT NULL DEFAULT 'staff'
                 CHECK (role IN ('owner', 'admin', 'staff', 'care', 'readonly')),
  last_seen_at   TEXT,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL,
  deleted_at     TEXT
);
CREATE UNIQUE INDEX idx_users_org_email ON users(org_id, email);

CREATE TABLE sessions (
  id           TEXT PRIMARY KEY,
  user_id      TEXT NOT NULL REFERENCES users(id),
  org_id       TEXT NOT NULL REFERENCES organizations(id),
  -- SHA-256 of the cookie value. The raw token is never stored.
  token_hash   TEXT NOT NULL UNIQUE,
  expires_at   TEXT NOT NULL,
  created_at   TEXT NOT NULL
);
CREATE INDEX idx_sessions_user ON sessions(user_id);
CREATE INDEX idx_sessions_expiry ON sessions(expires_at);

-- ── Households and members ───────────────────────────────────────────────────
-- A household is the sharing unit; a member is a person. Dependents are members
-- with a role of 'dependent' inside a household. Familia signals read this
-- structure directly, which is why household_members carries the relationship
-- and caregiving flags rather than burying them on the member row.

CREATE TABLE households (
  id                TEXT PRIMARY KEY,
  org_id            TEXT NOT NULL REFERENCES organizations(id),
  name              TEXT NOT NULL,
  -- Denormalized for cheap list rendering and Familia scoring. Recomputed on
  -- membership change; never authoritative over household_members.
  member_count      INTEGER NOT NULL DEFAULT 0,
  dependent_count   INTEGER NOT NULL DEFAULT 0,
  address_line1     TEXT,
  address_line2     TEXT,
  city              TEXT,
  state             TEXT,
  postal_code       TEXT,
  -- Monthly share amount in integer cents.
  share_amount_cents INTEGER NOT NULL DEFAULT 0,
  notes             TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL,
  deleted_at        TEXT
);
CREATE INDEX idx_households_org ON households(org_id, deleted_at);

CREATE TABLE members (
  id                 TEXT PRIMARY KEY,
  org_id             TEXT NOT NULL REFERENCES organizations(id),
  -- A member may exist before we know their household (common in messy imports).
  household_id       TEXT REFERENCES households(id),
  first_name         TEXT NOT NULL,
  last_name          TEXT NOT NULL,
  email              TEXT,
  phone              TEXT,
  date_of_birth      TEXT,                      -- 'YYYY-MM-DD'
  status             TEXT NOT NULL DEFAULT 'active'
                     CHECK (status IN ('active', 'pending', 'lapsed', 'inactive')),
  member_number      TEXT,                      -- the ministry's own external ID
  joined_at          TEXT,
  address_line1      TEXT,
  address_line2      TEXT,
  city               TEXT,
  state              TEXT,
  postal_code        TEXT,
  -- Normalized keys for dedupe. Written by src/lib/import/dedupe.ts so that
  -- matching is an index lookup, not a full scan with fuzzy logic in JS.
  dedupe_email       TEXT,                      -- lowercased, trimmed
  dedupe_phone       TEXT,                      -- digits only, last 10
  dedupe_name_dob    TEXT,                      -- 'last|first|YYYY-MM-DD'
  -- Engagement tracking — the raw material for Fides scoring.
  last_contact_at    TEXT,
  last_response_at   TEXT,
  onboarding_complete INTEGER NOT NULL DEFAULT 0,
  -- Staff-set flag feeding Onus. Explicit, never inferred.
  financial_stress   INTEGER NOT NULL DEFAULT 0,
  notes              TEXT,
  source             TEXT NOT NULL DEFAULT 'manual',  -- 'manual' | 'import' | 'api'
  created_at         TEXT NOT NULL,
  updated_at         TEXT NOT NULL,
  deleted_at         TEXT
);
CREATE INDEX idx_members_org_status ON members(org_id, status, deleted_at);
CREATE INDEX idx_members_household ON members(household_id);
-- The three dedupe paths, each an index hit.
CREATE INDEX idx_members_dedupe_email ON members(org_id, dedupe_email);
CREATE INDEX idx_members_dedupe_phone ON members(org_id, dedupe_phone);
CREATE INDEX idx_members_dedupe_name_dob ON members(org_id, dedupe_name_dob);
-- Keyset pagination on the members list: (last_name, id) > (?, ?).
CREATE INDEX idx_members_keyset ON members(org_id, last_name, id);

CREATE TABLE household_members (
  id             TEXT PRIMARY KEY,
  org_id         TEXT NOT NULL REFERENCES organizations(id),
  household_id   TEXT NOT NULL REFERENCES households(id),
  member_id      TEXT NOT NULL REFERENCES members(id),
  relationship   TEXT NOT NULL DEFAULT 'member'
                 CHECK (relationship IN ('primary', 'spouse', 'dependent', 'member', 'other')),
  -- Familia inputs. A caregiver in the household changes the shape of every
  -- care conversation, so it is a first-class column.
  is_caregiver   INTEGER NOT NULL DEFAULT 0,
  is_dependent   INTEGER NOT NULL DEFAULT 0,
  joined_at      TEXT,
  created_at     TEXT NOT NULL
);
CREATE UNIQUE INDEX idx_household_members_pair ON household_members(household_id, member_id);
CREATE INDEX idx_household_members_member ON household_members(member_id);

-- ── Import engine ────────────────────────────────────────────────────────────
-- An import is a durable, auditable object: the source file lands in R2, every
-- parsed row is persisted with its validation verdict, and nothing touches
-- `members` until a human commits the preview.

CREATE TABLE imports (
  id                TEXT PRIMARY KEY,
  org_id            TEXT NOT NULL REFERENCES organizations(id),
  created_by        TEXT REFERENCES users(id),
  filename          TEXT NOT NULL,
  -- R2 key under imports/<org>/<import_id>/source.csv
  r2_key            TEXT,
  file_size         INTEGER NOT NULL DEFAULT 0,
  format            TEXT NOT NULL DEFAULT 'csv' CHECK (format IN ('csv', 'xlsx')),
  status            TEXT NOT NULL DEFAULT 'uploaded'
                    CHECK (status IN ('uploaded', 'mapping', 'previewing', 'committing',
                                      'completed', 'failed', 'cancelled')),
  -- Header row as parsed, JSON array of strings.
  detected_headers  TEXT NOT NULL DEFAULT '[]',
  total_rows        INTEGER NOT NULL DEFAULT 0,
  valid_rows        INTEGER NOT NULL DEFAULT 0,
  invalid_rows      INTEGER NOT NULL DEFAULT 0,
  duplicate_rows    INTEGER NOT NULL DEFAULT 0,
  created_count     INTEGER NOT NULL DEFAULT 0,
  updated_count     INTEGER NOT NULL DEFAULT 0,
  skipped_count     INTEGER NOT NULL DEFAULT 0,
  error_message     TEXT,
  committed_at      TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL
);
CREATE INDEX idx_imports_org ON imports(org_id, created_at DESC);

CREATE TABLE import_rows (
  id             TEXT PRIMARY KEY,
  org_id         TEXT NOT NULL REFERENCES organizations(id),
  import_id      TEXT NOT NULL REFERENCES imports(id),
  row_number     INTEGER NOT NULL,              -- 1-based, matches the file
  raw            TEXT NOT NULL,                 -- JSON of the original row
  normalized     TEXT,                          -- JSON of canonical member fields
  action         TEXT NOT NULL DEFAULT 'create'
                 CHECK (action IN ('create', 'update', 'skip', 'error')),
  -- Why this row got its action. JSON array of {code, field, message, severity}.
  issues         TEXT NOT NULL DEFAULT '[]',
  matched_member_id TEXT REFERENCES members(id),
  match_reason   TEXT,                          -- 'email' | 'phone' | 'name_dob' | null
  committed      INTEGER NOT NULL DEFAULT 0,
  created_at     TEXT NOT NULL
);
CREATE INDEX idx_import_rows_import ON import_rows(import_id, row_number);
CREATE INDEX idx_import_rows_action ON import_rows(import_id, action);

CREATE TABLE import_mappings (
  id             TEXT PRIMARY KEY,
  org_id         TEXT NOT NULL REFERENCES organizations(id),
  import_id      TEXT REFERENCES imports(id),
  -- A named, reusable mapping ('Our old spreadsheet') is a saved template with
  -- import_id NULL. Per-import mappings carry the import_id.
  name           TEXT,
  -- JSON: { "<source header>": "<canonical field>" }
  mapping        TEXT NOT NULL DEFAULT '{}',
  is_template    INTEGER NOT NULL DEFAULT 0,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);
CREATE INDEX idx_import_mappings_org ON import_mappings(org_id, is_template);
CREATE INDEX idx_import_mappings_import ON import_mappings(import_id);

-- ── Sharing needs / case management ──────────────────────────────────────────

CREATE TABLE needs (
  id                  TEXT PRIMARY KEY,
  org_id              TEXT NOT NULL REFERENCES organizations(id),
  member_id           TEXT NOT NULL REFERENCES members(id),
  household_id        TEXT REFERENCES households(id),
  title               TEXT NOT NULL,
  description         TEXT,
  category            TEXT NOT NULL DEFAULT 'medical'
                      CHECK (category IN ('medical', 'surgical', 'maternity', 'emergency',
                                          'chronic', 'dental', 'vision', 'mental_health', 'other')),
  status              TEXT NOT NULL DEFAULT 'submitted'
                      CHECK (status IN ('submitted', 'in_review', 'needs_info', 'approved',
                                        'sharing', 'completed', 'declined', 'withdrawn')),
  -- Integer cents. Always.
  amount_requested_cents INTEGER NOT NULL DEFAULT 0,
  amount_approved_cents  INTEGER NOT NULL DEFAULT 0,
  amount_shared_cents    INTEGER NOT NULL DEFAULT 0,
  incident_date       TEXT,
  submitted_at        TEXT,
  -- Drives the Onus "overdue processing" rule.
  last_status_change_at TEXT,
  assigned_to         TEXT REFERENCES users(id),
  urgency             TEXT NOT NULL DEFAULT 'normal'
                      CHECK (urgency IN ('low', 'normal', 'high', 'critical')),
  created_at          TEXT NOT NULL,
  updated_at          TEXT NOT NULL,
  deleted_at          TEXT
);
CREATE INDEX idx_needs_org_status ON needs(org_id, status, deleted_at);
CREATE INDEX idx_needs_member ON needs(member_id);
CREATE INDEX idx_needs_stale ON needs(org_id, last_status_change_at);

CREATE TABLE need_updates (
  id           TEXT PRIMARY KEY,
  org_id       TEXT NOT NULL REFERENCES organizations(id),
  need_id      TEXT NOT NULL REFERENCES needs(id),
  author_id    TEXT REFERENCES users(id),
  kind         TEXT NOT NULL DEFAULT 'note'
               CHECK (kind IN ('note', 'status_change', 'document', 'payment', 'outreach')),
  body         TEXT,
  -- For status_change: JSON {from, to}. For payment: JSON {amount_cents}.
  meta         TEXT NOT NULL DEFAULT '{}',
  created_at   TEXT NOT NULL
);
CREATE INDEX idx_need_updates_need ON need_updates(need_id, created_at DESC);

-- ── Prayer board / care workflows ────────────────────────────────────────────

CREATE TABLE prayer_requests (
  id             TEXT PRIMARY KEY,
  org_id         TEXT NOT NULL REFERENCES organizations(id),
  member_id      TEXT REFERENCES members(id),
  household_id   TEXT REFERENCES households(id),
  need_id        TEXT REFERENCES needs(id),
  title          TEXT NOT NULL,
  body           TEXT,
  category       TEXT NOT NULL DEFAULT 'general'
                 CHECK (category IN ('general', 'health', 'hospitalization', 'bereavement',
                                     'birth', 'financial', 'family', 'spiritual')),
  status         TEXT NOT NULL DEFAULT 'open'
                 CHECK (status IN ('open', 'praying', 'answered', 'closed')),
  visibility     TEXT NOT NULL DEFAULT 'staff'
                 CHECK (visibility IN ('staff', 'members', 'public')),
  is_urgent      INTEGER NOT NULL DEFAULT 0,
  prayer_count   INTEGER NOT NULL DEFAULT 0,
  -- Care workflow: who owns follow-up, and when it is due.
  assigned_to    TEXT REFERENCES users(id),
  followup_due_at TEXT,
  last_followup_at TEXT,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL,
  deleted_at     TEXT
);
CREATE INDEX idx_prayer_org_status ON prayer_requests(org_id, status, deleted_at);
CREATE INDEX idx_prayer_member ON prayer_requests(member_id);
CREATE INDEX idx_prayer_followup ON prayer_requests(org_id, followup_due_at);

-- ── NRI: Need Response Intelligence ──────────────────────────────────────────
-- A signal is one directional reading about one subject, produced by a named
-- rule. It carries its own reasons so the UI never has to re-derive "why".
-- Signals are derived data: they can always be rebuilt from D1 by
-- src/lib/nri/engine.ts. That is what makes them safe to cache and recompute.

CREATE TABLE member_signals (
  id             TEXT PRIMARY KEY,
  org_id         TEXT NOT NULL REFERENCES organizations(id),
  -- Polymorphic subject: a signal can hang off a member, a household, or a need.
  subject_type   TEXT NOT NULL DEFAULT 'member'
                 CHECK (subject_type IN ('member', 'household', 'need')),
  subject_id     TEXT NOT NULL,
  direction      TEXT NOT NULL CHECK (direction IN ('cura', 'onus', 'familia', 'fides')),
  -- 0–100. Bounded so the UI can render it without knowing the rule set.
  score          INTEGER NOT NULL DEFAULT 0,
  -- JSON array of {code, label, weight, detail}. The audit trail of the score.
  reason_codes   TEXT NOT NULL DEFAULT '[]',
  -- Which rule pass produced this: 'rules.v1' today, room for more later.
  source         TEXT NOT NULL DEFAULT 'rules.v1',
  -- Staff can dismiss a signal; dismissal is per-signal and survives recompute
  -- until the underlying facts change enough to raise the score again.
  dismissed      INTEGER NOT NULL DEFAULT 0,
  dismissed_by   TEXT REFERENCES users(id),
  dismissed_at   TEXT,
  -- Score at the moment of dismissal. If a recompute exceeds this materially,
  -- the signal resurfaces — dismissing "member is quiet" should not hide
  -- "member is quiet AND now hospitalized".
  dismissed_at_score INTEGER,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);
-- One live signal per (subject, direction, source) — recompute upserts.
CREATE UNIQUE INDEX idx_signals_subject_direction
  ON member_signals(org_id, subject_type, subject_id, direction, source);
-- The command center's main query: highest live scores in the org.
CREATE INDEX idx_signals_triage ON member_signals(org_id, dismissed, score DESC);
CREATE INDEX idx_signals_direction ON member_signals(org_id, direction, score DESC);

-- Per-user, per-org NRI UI state. This is the "dismissed / recently seen"
-- layer: which nudges are hidden today, when the compass last auto-opened, and
-- how far through the guide the user has gotten. Cross-device by design, which
-- is why it lives in D1 rather than localStorage.
CREATE TABLE nri_sessions (
  id                   TEXT PRIMARY KEY,
  org_id               TEXT NOT NULL REFERENCES organizations(id),
  user_id              TEXT NOT NULL REFERENCES users(id),
  -- JSON array of nudge ids dismissed on dismissed_date.
  dismissed_nudge_ids  TEXT NOT NULL DEFAULT '[]',
  dismissed_date       TEXT,                    -- 'YYYY-MM-DD', local calendar day
  last_auto_open_at    TEXT,
  -- JSON array of guide section titles already shown.
  guide_sections_seen  TEXT NOT NULL DEFAULT '[]',
  guide_completed_at   TEXT,
  -- The posture the engine last inferred, for continuity across page loads.
  last_posture         TEXT,
  created_at           TEXT NOT NULL,
  updated_at           TEXT NOT NULL
);
CREATE UNIQUE INDEX idx_nri_sessions_user ON nri_sessions(org_id, user_id);

-- ── Documents (R2 metadata lives here; bytes live in R2) ─────────────────────

CREATE TABLE documents (
  id            TEXT PRIMARY KEY,
  org_id        TEXT NOT NULL REFERENCES organizations(id),
  -- What this document is attached to.
  subject_type  TEXT NOT NULL DEFAULT 'member'
                CHECK (subject_type IN ('member', 'household', 'need', 'import', 'org')),
  subject_id    TEXT,
  -- Full R2 object key. Unique so a retry can never silently overwrite.
  r2_key        TEXT NOT NULL UNIQUE,
  filename      TEXT NOT NULL,
  content_type  TEXT NOT NULL DEFAULT 'application/octet-stream',
  size_bytes    INTEGER NOT NULL DEFAULT 0,
  uploaded_by   TEXT REFERENCES users(id),
  created_at    TEXT NOT NULL,
  deleted_at    TEXT
);
CREATE INDEX idx_documents_subject ON documents(org_id, subject_type, subject_id);

-- ── Audit log ────────────────────────────────────────────────────────────────
-- Every write that a human would want explained after the fact. NRI recomputes
-- write here too — "why did this member surface" must be answerable months later.

CREATE TABLE audit_log (
  id            TEXT PRIMARY KEY,
  org_id        TEXT NOT NULL REFERENCES organizations(id),
  actor_id      TEXT REFERENCES users(id),
  actor_kind    TEXT NOT NULL DEFAULT 'user'
                CHECK (actor_kind IN ('user', 'system', 'queue', 'import')),
  action        TEXT NOT NULL,                  -- 'member.created', 'nri.recompute', …
  subject_type  TEXT,
  subject_id    TEXT,
  meta          TEXT NOT NULL DEFAULT '{}',     -- JSON
  created_at    TEXT NOT NULL
);
CREATE INDEX idx_audit_org_time ON audit_log(org_id, created_at DESC);
CREATE INDEX idx_audit_subject ON audit_log(org_id, subject_type, subject_id);

-- ── White-label CMS shell ────────────────────────────────────────────────────
-- Ministry-branded member-facing portals. Pages are ordered blocks so the
-- builder can grow without a schema change per block type.

CREATE TABLE cms_pages (
  id            TEXT PRIMARY KEY,
  org_id        TEXT NOT NULL REFERENCES organizations(id),
  slug          TEXT NOT NULL,
  title         TEXT NOT NULL,
  -- JSON array of {type, ...props}. Rendered by src/features/cms.
  blocks        TEXT NOT NULL DEFAULT '[]',
  status        TEXT NOT NULL DEFAULT 'draft'
                CHECK (status IN ('draft', 'published')),
  published_at  TEXT,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL,
  deleted_at    TEXT
);
CREATE UNIQUE INDEX idx_cms_pages_slug ON cms_pages(org_id, slug);
