import { useMemo } from 'react';
import { Download, Info } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { generateAssets } from '@/lib/brand/assets';
import type { ResolvedBrand } from '@/lib/brand/tokens';

/**
 * The generated assets.
 *
 * These sit under the studio rather than on their own page because they are not
 * a separate decision — they are what the colour and typeface already chosen
 * imply. Somebody who changes the primary colour should watch these change
 * underneath it, which is the fastest way to understand that they will not have
 * to redo anything later.
 *
 * The caveats are shown next to the assets they apply to, not in a footnote. A
 * ministry that uploads an SVG to Facebook and gets a blank preview will not
 * connect it back to a sentence in the documentation.
 */
export function BrandAssets({
  brand, name, tagline,
}: {
  brand: ResolvedBrand;
  name: string;
  tagline?: string;
}) {
  const assets = useMemo(
    () => generateAssets({ brand, name, tagline }),
    [brand, name, tagline],
  );

  function download(filename: string, svg: string) {
    // A Blob rather than a data URI: Safari refuses to download a data: URL
    // from a link click, and silently doing nothing is the worst failure a
    // download button has.
    const url = URL.createObjectURL(new Blob([svg], { type: 'image/svg+xml' }));
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base">Your assets</CardTitle>
        <p className="text-sm text-muted-foreground">
          Generated from the colour and typeface above, so they cannot end up disagreeing with your
          site. Change the colour and these change with it.
        </p>
      </CardHeader>

      <CardContent className="space-y-6">
        {assets.map((asset) => (
          <div key={asset.key} className="grid gap-3 sm:grid-cols-[14rem_1fr] sm:items-start">
            <div
              // The generated SVGs carry intrinsic width and height, which is
              // right for a downloaded file and wrong in a fixed-width column:
              // a 512-square mark and a 1200x630 card both letterbox into tall
              // empty boxes. viewBox already carries the aspect ratio, so the
              // preview overrides the intrinsic size and lets each one scale.
              className="flex items-center justify-center rounded-md border bg-white p-3 [&>svg]:h-auto [&>svg]:w-full"
              // The SVG is generated by us from a fixed template with every
              // interpolated value escaped — there is no path by which a
              // ministry's own input reaches this as markup.
              dangerouslySetInnerHTML={{ __html: asset.svg }}
            />
            <div className="space-y-1.5">
              <p className="text-sm font-medium">{asset.label}</p>
              <p className="text-sm text-muted-foreground">{asset.note}</p>
              {asset.caveat && (
                <p className="flex items-start gap-1.5 text-xs text-amber-700 dark:text-amber-500">
                  <Info className="mt-0.5 h-3.5 w-3.5 shrink-0" />
                  {asset.caveat}
                </p>
              )}
              <Button size="sm" variant="outline" onClick={() => download(asset.filename, asset.svg)}>
                <Download className="mr-1.5 h-4 w-4" /> {asset.filename}
              </Button>
            </div>
          </div>
        ))}
      </CardContent>
    </Card>
  );
}
