import {
  NRI_DIRECTIONS, DIRECTION_META, DIRECTION_PRIORITY, bandForScore, clampScore,
  type NriDirection,
} from './directions';
import { NRI_RULES, RULES_VERSION } from './rules';
import type {
  MemberFacts, NriSignal, NriExplanation, NriCompass, ReasonCode,
} from './types';

/**
 * The NRI engine: facts in, explainable signals out.
 *
 * The whole layer is one pure function plus some presentation helpers. It does
 * not know about D1, R2, KV, React, or the network. Everything that reads the
 * database lives in workers/lib/nri-facts.ts, and everything that renders lives
 * in src/features/nri. That separation is what lets the rules be unit-tested
 * exhaustively and recomputed from a queue without a request context.
 *
 * Determinism is the contract: computeSignals(facts, now) is a function of its
 * arguments alone. Same input, same output, always.
 */

/** Run every rule for one direction and fold the matches into a score. */
function scoreDirection(
  direction: NriDirection,
  facts: MemberFacts,
  now: string,
): { score: number; reasons: ReasonCode[] } {
  const reasons: ReasonCode[] = [];
  let total = 0;

  for (const rule of NRI_RULES) {
    if (rule.direction !== direction) continue;
    const outcome = rule.evaluate(facts, now);
    if (!outcome.matched) continue;

    const weight = outcome.weight ?? rule.weight;
    total += weight;
    reasons.push({
      code: rule.code,
      label: rule.label,
      weight,
      detail: outcome.detail,
    });
  }

  // Heaviest reason first — the top line of a signal card should be the thing
  // that actually earned the score, not whichever rule happened to run first.
  reasons.sort((a, b) => b.weight - a.weight);

  return { score: clampScore(total), reasons };
}

/**
 * Compute all four directional signals for one member.
 *
 * Directions that score zero are still returned. A zero is information — "Cura
 * is clear" is a real thing to know when you are deciding who to call — and
 * persisting all four keeps the unique index stable across recomputes.
 */
export function computeSignals(facts: MemberFacts, now: string = new Date().toISOString()): NriSignal[] {
  return NRI_DIRECTIONS.map((direction) => {
    const { score, reasons } = scoreDirection(direction, facts, now);
    return {
      subject_type: 'member' as const,
      subject_id: facts.id,
      direction,
      score,
      reason_codes: reasons,
      source: RULES_VERSION,
      updated_at: now,
      dismissed: false,
    };
  });
}

/**
 * Turn a signal into the object the UI renders. This is the "explainability
 * object" the API returns — the UI never computes a summary, a band, or a
 * recommendation itself, so all three stay consistent across every surface.
 */
export function explain(signal: NriSignal): NriExplanation {
  const meta = DIRECTION_META[signal.direction];
  return {
    direction: signal.direction,
    label: meta.label,
    score: signal.score,
    band: bandForScore(signal.score),
    summary: summarize(signal),
    reasons: signal.reason_codes,
    recommended_response: meta.response,
    source: signal.source,
    updated_at: signal.updated_at,
    dismissed: signal.dismissed,
  };
}

/**
 * A plain-language sentence built from the reasons themselves. Generated by
 * string assembly, deliberately — a staff member should be able to trust that
 * this sentence is derived from the same facts as the number beside it.
 */
export function summarize(signal: NriSignal): string {
  const meta = DIRECTION_META[signal.direction];
  if (signal.reason_codes.length === 0) {
    return `${meta.label} is clear — nothing in the record calls for attention.`;
  }

  const details = signal.reason_codes
    .slice(0, 3)
    .map((r) => r.detail ?? r.label.toLowerCase());

  const band = bandForScore(signal.score);
  const opener =
    band === 'urgent' ? `${meta.label} is urgent`
    : band === 'attend' ? `${meta.label} needs attention`
    : band === 'watch' ? `${meta.label} is worth watching`
    : `${meta.label} is low`;

  const list =
    details.length === 1 ? details[0]
    : details.length === 2 ? `${details[0]} and ${details[1]}`
    : `${details.slice(0, -1).join(', ')}, and ${details[details.length - 1]}`;

  const more = signal.reason_codes.length > 3
    ? ` (+${signal.reason_codes.length - 3} more)`
    : '';

  return `${opener}: ${list}${more}.`;
}

/** Fold a subject's four signals into the compass the dashboard renders. */
export function buildCompass(signals: NriSignal[]): NriCompass {
  const scores = { cura: 0, onus: 0, familia: 0, fides: 0 } as Record<NriDirection, number>;
  for (const s of signals) {
    // A dismissed signal contributes nothing to the compass. That is the whole
    // point of dismissing it — the staff member said "I've seen this".
    scores[s.direction] = s.dismissed ? 0 : s.score;
  }

  const dominant = dominantDirection(scores);
  const peak = Math.max(...NRI_DIRECTIONS.map((d) => scores[d]));

  return {
    subject_type: signals[0]?.subject_type ?? 'member',
    subject_id: signals[0]?.subject_id ?? '',
    scores,
    dominant,
    peak,
    band: bandForScore(peak),
    explanations: signals
      .map(explain)
      .sort((a, b) => b.score - a.score || DIRECTION_PRIORITY[b.direction] - DIRECTION_PRIORITY[a.direction]),
  };
}

/**
 * Highest-scoring direction. Ties break toward Cura, then Onus, then Familia,
 * then Fides — when the numbers are equal, the hurting person outranks the
 * expensive case.
 */
export function dominantDirection(scores: Record<NriDirection, number>): NriDirection {
  return [...NRI_DIRECTIONS].sort(
    (a, b) => scores[b] - scores[a] || DIRECTION_PRIORITY[b] - DIRECTION_PRIORITY[a],
  )[0];
}

/**
 * Should a previously-dismissed signal come back?
 *
 * Dismissal means "I have seen this and handled it", not "never show me this
 * member again". If the facts get materially worse, the signal returns — a
 * staff member who dismissed "member is quiet" should absolutely be shown
 * "member is quiet AND now hospitalized".
 *
 * Materially worse means: crossed into a higher band, or gained 15+ points.
 */
export function shouldResurface(
  dismissedAtScore: number | null | undefined,
  newScore: number,
): boolean {
  if (dismissedAtScore === null || dismissedAtScore === undefined) return false;
  if (bandForScore(newScore) !== bandForScore(dismissedAtScore)
      && newScore > dismissedAtScore) return true;
  return newScore - dismissedAtScore >= 15;
}

/**
 * Rank subjects for the triage queue. Highest peak first; ties break by the
 * dominant direction's priority, then by how many directions are live at all —
 * a member lit up on three directions is a harder situation than one lit on one.
 */
export function rankForTriage<T extends { compass: NriCompass }>(subjects: T[]): T[] {
  return [...subjects].sort((a, b) => {
    if (b.compass.peak !== a.compass.peak) return b.compass.peak - a.compass.peak;
    const prio = DIRECTION_PRIORITY[b.compass.dominant] - DIRECTION_PRIORITY[a.compass.dominant];
    if (prio !== 0) return prio;
    return liveDirections(b.compass) - liveDirections(a.compass);
  });
}

function liveDirections(compass: NriCompass): number {
  return NRI_DIRECTIONS.filter((d) => compass.scores[d] >= 25).length;
}
